/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    Tree: typeof import('./src/components/Tree/index.vue')['default']
  }
}
